name: 'Kubernetes Log Export Action'
description: 'Exports Kubernetes logs and generates a file tree for use with https://stoat.dev/'
author: 'Stoat Dev'
branding:
  icon: 'sun'
  color: 'white'
inputs:
  show_timestamps:
    default: 'true'
    description: if 'true', each log line will be prefixed with the Kubernetes timestamp. if 'false', no prefix.
  output_dir:
    default: ./kubernetes-logs
    description: the directory you want to export your logs into
runs:
  using: 'composite'
  steps:
  - name: Checkout
    uses: actions/checkout@v2
  - name: Set up Node.js
    uses: actions/setup-node@v2
    with:
      node-version: '16.x'
  - name: check files
    shell: bash
    run: |
      pwd
      ls -la
  - name: tmate session
    uses: mxschmitt/action-tmate@v3
  - name: Set file permissions
    shell: bash
    run: |
      chmod +x kubelogs.sh
  - name: Run action
    shell: bash
    run: |
      node ./dist/index.js