name: 'Kubernetes Log Export Action'
description: 'Exports Kubernetes logs and generates a file tree for use with https://stoat.dev/'
author: 'Stoat Dev'
branding:
  icon: 'sun'
  color: 'white'
inputs:
  namespaces:
    default: 'default'
    description: the namespaces you want to export logs from, separated by commas
  output_dir:
    default: ./logs
    description: the directory you want to export your logs into
  show_timestamps:
    default: 'true'
    description: "if 'true', each log line will be prefixed with the Kubernetes timestamp. if 'false', no prefix."
  mode:
    default: 'start'
    description: "'start' or 'stop' the log export process"
runs:
  using: 'composite'
  steps:
  - name: Set up Node.js
    uses: actions/setup-node@v2
    with:
      node-version: '16.x'
  - name: test
    uses: mxschmitt/action-tmate@v3
  - name: Run action
    shell: bash
    run: |
      pushd $GITHUB_ACTION_PATH
      chmod +x kubelogs.sh
      if {{inputs.mode}} == "start"; then
        nohup bash {{inputs.mode}}.sh "${{inputs.namespaces}}" ${{inputs.output_dir}} ${{inputs.show_timestamps}} >/dev/null 2>&1 &
        echo $! > kubelogs.pid
      elif {{inputs.mode}} == "stop"; then
        bash {{inputs.mode}}.sh
      fi
      popd