name: 'Kubernetes Log Export Action'
description: 'Exports Kubernetes logs and generates a file tree for use with https://stoat.dev/'
author: 'Stoat Dev'
branding:
  icon: 'sun'
  color: 'white'
inputs:
  show_timestamps:
    default: 'true'
    description: if 'true', each log line will be prefixed with the Kubernetes timestamp. if 'false', no prefix.
  output_dir:
    default: ./kubernetes-logs
    description: the directory you want to export your logs into
runs:
  using: 'composite'
  steps:
  - name: Set up Node.js
    uses: actions/setup-node@v2
    with:
      node-version: '16.x'
  - name: test
    shell: bash
    run: |
      echo "test here"
  - name: Run action
    shell: bash
    run: |
      pushd $GITHUB_ACTION_PATH
      chmod +x kubelogs.sh
      if $MODE == "start"; then
        nohup bash $MODE.sh "$NAMESPACES" $OUTPUT_DIR $SHOW_TIMESTAMPS >/dev/null 2>&1 &
        echo $! > kubelogs.pid
      elif $MODE == "stop"; then
        bash $MODE.sh
      fi
      popd